apiVersion: apps/v1
kind: Deployment
metadata:
  name: minipaas-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      infrastructure: redis
  template:
    metadata:
      labels:
        infrastructure: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        command: ["redis-server", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    infrastructure: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379